#!/bin/bash

# unset irrelevant variables
## TRJ - Command below was generating an error
##deactivate nondestructive

VIRTUAL_ENV="/home/sundial/volttronproj/env"
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH

# unset PYTHONHOME if set
if ! [ -z "${PYTHONHOME+_}" ] ; then
    _OLD_VIRTUAL_PYTHONHOME="$PYTHONHOME"
    unset PYTHONHOME
fi

if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT-}" ] ; then
    _OLD_VIRTUAL_PS1="$PS1"
    if [ "x(volttron)" != x ] ; then
        PS1="(volttron)$PS1"
    else
        PS1="(`basename \"$VIRTUAL_ENV\"`) $PS1"
    fi
    export PS1
fi

# Make sure to unalias pydoc if it's already there
alias pydoc 2>/dev/null >/dev/null && unalias pydoc

pydoc () {
    python -m pydoc "$@"
}

## TRJ -- Sounds like we dont need it in our volttron launcher
## This should detect bash and zsh, which have a hash command that must
## be called to get it to forget past commands.  Without forgetting
## past commands the $PATH changes we made may not be respected
#if [ -n "${BASH-}" ] || [ -n "${ZSH_VERSION-}" ] ; then
#    hash -r 2>/dev/null
#fi

echo "shutting down volttron..."
volttron-ctl shutdown

sleep 5
tough_pid=`pgrep "volttron"`
if [ -n "$tough_pid" ]; then 
  echo "volttron won't die..."
  sleep 10
  kill $tough_pid
fi

echo "shutdown."

# finally kill off the pid file too
rm -f pids/volttron.pid
echo "pid cleanup complete."
