#!/usr/bin/env bash

if [ ! -d "volttron"; then
  echo "make-scaffoldagent script must be run from the volttron project directory." 
  exit
fi

# Build a temp file string for use with the configuration
export CONFIG=$(mktemp /tmp/cfg-scaffoldagent.XXXXXX)

# Put contents of the config file in between the EOL markers.
# NOTE: Be mindful of the commas this is JSON (except for the comments)
#       not python.  Trailing ',' are an error.
cat > $CONFIG <<EOL
{
    # log-level can be DEBUG, INFO, WARN or ERROR
    # verbosity is decreased from left to right above
    # default: INFO
    "log-level": "DEBUG",

    # This will be printed in the context of the heartbeat.
    "message": "heartbeat-scaffoldagent",

    # The heartbeat period in seconds to print a message for knowing the
    # agent is still working.
    # Note: 0 for no heartbeat
    "heartbeat_period": 5
}
EOL

export SOURCE=services/contrib/ScaffoldAgent/
export TAG=scaffoldagent

# Uncomment this to set the identity of the agent. Overrides the platform default identity and the agent's
# preferred identity.
export AGENT_VIP_IDENTITY=scaffoldagent

# Add NO_START parameter if the agent shouldn't start
# export NO_START=1

./scripts/core/make-agent.sh 

# To set the agent to autostart with the platform, pass "enable" 
# to make-agent.sh: ./scripts/core/make-agent.sh enable

# Finally remove the temporary config file
rm $CONFIG
